#server 服务
server:
     port: 8080
     session-timeout: 10

#dataSource 数据库
spring:
    datasource:
         url: jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = orcl)))
         username: test
         password: lychee
         driver-class-name: oracle.jdbc.driver.OracleDriver
         max-wait: 10000
         initial-size: 5

#mybatis XML文件位置
mybatis:
     mapperLocations: classpath:mapper/*.xml
     type-aliases-package: com.lychee.entity
